name: Build Server

on:
  push:
  workflow_dispatch:

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cache
        id: cache-key
        run: echo "CLIENT_CACHE_KEY=client-cache-${{ hashFiles('client/**') }}" >> $GITHUB_OUTPUT
      - uses: actions/cache/restore@v4
        id: restore-cache
        with:
          path: server/static
          key: ${{ steps.cache-key.outputs.CLIENT_CACHE_KEY }}
      - name: Setup node
        if: ${{ !steps.restore-cache.outputs.cache-hit }}
        uses: actions/setup-node@v4
        with:
          node-version: latest
          architecture: x64
          check-latest: true
          cache: npm
          cache-dependency-path: "**/package.json"
      - name: Build client
        if: ${{ !steps.restore-cache.outputs.cache-hit }}
        run: |
          cd client
          npm install
          NODE_OPTIONS=--openssl-legacy-provider npm run build
      - uses: actions/cache/save@v4
        if: ${{ !steps.restore-cache.outputs.cache-hit }}
        with:
          path: server/static
          key: ${{ steps.cache-key.outputs.CLIENT_CACHE_KEY }}
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: static
          path: server/static

  build-server:
    runs-on: ubuntu-latest
    needs: [build-client]
    strategy:
      fail-fast: false
      matrix:
        include:
          - { target: x86_64-windows-gnu,      upx: "upx", ext: ".exe" }
          - { target: x86-windows-gnu,         upx: "upx", ext: ".exe" }
          - { target: aarch64-windows-gnu,     upx: "ls",  ext: ".exe" }
          - { target: x86_64-linux-gnu,        upx: "upx" }
          - { target: x86-linux-gnu,           upx: "upx" }
          - { target: aarch64-linux-gnu,       upx: "upx" }
          - { target: x86_64-linux-musl,       upx: "upx" }
          - { target: x86-linux-musl,          upx: "upx" }
          - { target: aarch64-linux-musl ,     upx: "upx" }
          - { target: mipsel-linux-musl,       upx: "upx --lzma" }
          - { target: x86_64-macos.11.0-none,  upx: "ls" }
          - { target: aarch64-macos.11.0-none, upx: "ls" }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        name: static
      - name: strip static
        run: |
          find static -name "*.br" -type f -delete
          find static -name "*.css" -type f -delete
          find static -name "*.js" -type f -delete
          find static -name "*.html" -type f -delete
          find static -name "*.svg" -type f -delete
      - name: Install UPX
        if: matrix.upx != 'ls'
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - name: Build executable
        run: |
          mv static server-c/
          mkdir -p server-c/build
          cd server-c/build
          cmake -DZIG_TARGET=${{ matrix.target }} -DPACKAGE_FILE=ON -DCMAKE_BUILD_TYPE=MinSizeRel ..
          cmake --build .
          sudo apt-get install llvm --no-install-recommends
          llvm-strip cloud_clipboard${{ matrix.ext }}
          upx --version
          ${{ matrix.upx }} cloud_clipboard${{ matrix.ext }}
          tar -czvf cloud_clipboard.tar.gz cloud_clipboard${{ matrix.ext }}
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: server-c/build/cloud_clipboard.tar.gz
